{"stats": {"errors": 0, "failures": 8, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 8}, "results": [{"classname": "index_test:TestRegression", "name": "test_attendance", "time": 0.000362396240234375, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != 150", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/johann/single-variable-regression-lab-data-science-intro-000/test/index_test.py\", line 7, in test_attendance\n    self.assertEqual(attendance(100), 150)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != 150\n"}, {"classname": "index_test:TestRegression", "name": "test_attendance_with_friends", "time": 0.0002951622009277344, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != 170", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/johann/single-variable-regression-lab-data-science-intro-000/test/index_test.py\", line 11, in test_attendance_with_friends\n    self.assertEqual(attendance_with_friends(100), 170)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != 170\n"}, {"classname": "index_test:TestRegression", "name": "test_build_starting_line", "time": 0.0002689361572265625, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != {'b': 10.0, 'm': 1.725}", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/johann/single-variable-regression-lab-data-science-intro-000/test/index_test.py\", line 37, in test_build_starting_line\n    self.assertEqual(build_starting_line([0, 200, 400], [10, 400, 700]), {'b': 10.0, 'm': 1.725})\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != {'b': 10.0, 'm': 1.725}\n"}, {"classname": "index_test:TestRegression", "name": "test_expected_value_for_line", "time": 0.00024580955505371094, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != 250", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/johann/single-variable-regression-lab-data-science-intro-000/test/index_test.py\", line 40, in test_expected_value_for_line\n    self.assertEqual(expected_value_for_line(1.5, 100, 100), 250)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != 250\n"}, {"classname": "index_test:TestRegression", "name": "test_m_b_data", "time": 0.0003020763397216797, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != {'x': [0, 50, 100], 'y': [20.0, 95.0, 170.0]}", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/johann/single-variable-regression-lab-data-science-intro-000/test/index_test.py\", line 15, in test_m_b_data\n    self.assertEqual(m_b_data(1.5, 20, [0, 50, 100]), {'x': [0, 50, 100], 'y': [20.0, 95.0, 170.0]})\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != {'x': [0, 50, 100], 'y': [20.0, 95.0, 170.0]}\n"}, {"classname": "index_test:TestRegression", "name": "test_m_b_trace", "time": 0.00023818016052246094, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != {'mode': 'line', 'name': 'line function',[40 chars]0.0]}", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/johann/single-variable-regression-lab-data-science-intro-000/test/index_test.py\", line 19, in test_m_b_trace\n    self.assertEqual(m_b_trace(1.5, 20, [0, 50, 100]), trace)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != {'mode': 'line', 'name': 'line function',[40 chars]0.0]}\n"}, {"classname": "index_test:TestRegression", "name": "test_marginal_return_on_budget", "time": 0.0001285076141357422, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != 1.5", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/johann/single-variable-regression-lab-data-science-intro-000/test/index_test.py\", line 27, in test_marginal_return_on_budget\n    self.assertEqual(marginal_return_on_budget(first_show, second_show), 1.5)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != 1.5\n"}, {"classname": "index_test:TestRegression", "name": "test_y_intercept", "time": 0.0001480579376220703, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != 100", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/johann/single-variable-regression-lab-data-science-intro-000/test/index_test.py\", line 33, in test_y_intercept\n    self.assertEqual(y_intercept(budgets, attendance), 100)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != 100\n"}]}